### ISSUE TITLE
GDS Projection from polars / pandas dataframe or arrow table

### ISSUE THREAD

**Issue by Mintactus** [neo4j/graph-data-science#312] opened 2024-05-30 16:25 UTC
The new [Polars](https://pola.rs/) dataframe multi engine is absolutely a must in the data industry.
After using it for months, the performance benifits are insane, adios pandas, your time has come.

Allowing GDS to export as and create projections from polars  dataframes would be natural today. ( At least once Polars will be out of Alpha )

Even better, GDS being based on apache arrow, I think it would make sens for GDS to create projection directly from an arrow table ? This will makes it agnostic to the engine processing the data.

**Comment by Mats-SX** [comment] 2024-06-03 13:17
Duplicate of #308

**Closed by Mats-SX** 2024-06-03 13:17 UTC
Labels: feature request
