### ISSUE TITLE
Shortest paths using multiple relationship types

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#184] opened 2022-04-20 18:32 UTC
When a user has multiple relationship types in their shortest path, the engine doesn't recognize that all relationship types need to have the particular relationship weight.

Using GDS 2.0.1

Create graph:

```
CREATE (:Stop)-[:TRAM {duration:5}]->(:Stop)-[:WALK]->(:Stop)
```

Project a graph

```
CALL gds.graph.project('test', 'Stop', ['TRAM', 'WALK'], {relationshipProperties:['duration']})
```

Run Dijkstra shortest path:

```
MATCH (s:Stop),(t:Stop)
WHERE NOT EXISTS {()-->(s)} AND NOT EXISTS {(t)-->()}
CALL gds.shortestPath.dijkstra.stream('test',{sourceNode:s, targetNode: t, relationshipWeightProperty:'duration'})
YIELD nodeIds, costs
RETURN nodeIds, costs
```

Results

nodeIds | costs
-- | --
[0, 1, 2] | [0.0, 5.0, NaN]

You can observer the NaN values. I think it would be preferred to omit users to be able to return shortest paths with NaN values for cost.

**Comment by Mats-SX** [comment] 2022-04-26 15:24
If you add a `defaultValue` to your relationship projection, does that fix the issue?

```
CALL gds.graph.project(
  'test', 
  'Stop', 
  { TRAM: { properties: {duration: { defaultValue: 0 }}}, WALK: { properties: {duration: { defaultValue: 0 }}} } 
)
```

**Comment by tomasonjo** [comment] 2022-04-26 17:38
Ok, I get it. Just a behavior I noticed, how you handle it is up to you :)

Closing for now

**Comment by Mats-SX** [comment] 2022-04-28 12:20
@tomasonjo I appreciate very much that you created the issue! Maybe a default default value of `0` would be more useful than default default of `NaN`.

**Comment by s1ck** [comment] 2022-05-09 10:35
I investigated it and came to the conclusion that Dijkstra behaves exactly as expected. The problem is - as Mats already pointed out - the default value for the `WALK` relationship. Using `relationshipProperties` in the project procedure, is shorthand for saying "all projected relationship types have that property and the default value is NaN`. 

If the relationship projection would be written as 

```
{ 
    TRAM: { properties: { duration: { defaultValue: 0 }}}, 
    WALK: { } 
} 
```

the in-memory graph would have no property assigned to the `WALK` relationship, which - when executing Dijkstra - would trigger the _algorithm specific_ fallback value of `1.0`.

Hope this clarifies things.

**Closed by s1ck** 2022-05-09 10:35 UTC
Labels: BUG

**Comment by tomasonjo** [comment] 2022-05-09 12:38
> the in-memory graph would have no property assigned to the WALK relationship, which - when executing Dijkstra - would trigger the algorithm specific fallback value of 1.0

Perhaps adding this line  to the docs would make sense

**Comment by s1ck** [comment] 2022-05-09 12:46
I agree. We're discussing to either make it more prominent in the docs _or_ to change the behaviour of `relationshipProperties` to only make it available for relationship types that actually have that property. Wdyt?
