### ISSUE TITLE
Typo in the versions.json file

### ISSUE THREAD

**Issue by BalmungSan** [neo4j/graph-data-science#100] opened 2021-02-01 12:59 UTC
Hello,

The current [versions.json file](https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/versions.json) has a typo for the two `4.1.6` and `4.2.3` versions of **neo4j**.

It says that the **jar** URL should be: https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/neo4j-graph-data-science-1.4.1.jar
Which doesn't work, because it should be: https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/neo4j-graph-data-science-1.4.1-standalone.jar
_(note the "standalone" at the end)_.

**Comment by vnickolov** [comment] 2021-02-01 13:11
@BalmungSan thank you very much for pointing this out!
The file should now be updated, can you please verify and close the issue.

**Comment by BalmungSan** [comment] 2021-02-01 13:13
@vnickolov thanks for the quick response.
I can confirm the file is updated I am re-running some jobs that failed due to this, if they work as expected _(which they should)_ I will close this. 🙂

**Closed** 2021-02-01 13:24 UTC

**Comment by BalmungSan** [comment] 2021-02-10 00:07
Hi @vnickolov it seems it happened again  with `1.5.0`

**Comment by vnickolov** [comment] 2021-02-10 05:02
Hi @BalmungSan thank you for pointing this out, we will look into it, should be a quick thing to fix.

**Comment by vnickolov** [comment] 2021-02-10 05:06
@BalmungSan the entry is updated, we will still look for the cause so we don't get this in the future, sorry for the inconvenience.

**Comment by BalmungSan** [comment] 2021-02-10 05:14
Thanks again! @vnickolov

Maybe this helps, I am 99% dure that with the preview release it was correctly released.

Because I first got an error due the changes in the shortest path algorithms, fixed the code and test it in local and then after pushing again it failed again in CI but this time because it couldn't download the jar; when I noticed that I checked the releases page again and noticed it was not longer a preview but a latest release and that it was done like 20 minutes before.

I even thought that maybe it was just that the jar uploading process would take some time or something, so I decided to wait for a while before commenting again.

**Comment by vnickolov** [comment] 2021-02-10 05:53
Thank you @BalmungSan, 

Yes, we did release `GDS 1.5.0` yesterday.
We are confident that the release was alright, this is more of a naming issue during generation of the `versions.json` file entry. We are going to fix this as soon as we can.

Thank you once again for reaching out!

**Comment by BalmungSan** [comment] 2021-02-10 12:21
@vnickolov yeah, what I mean is that the preview release produced the correct name in the `version.json` file. It was during the promotion of that preview to the official latest release that it went wrong.

**Comment by BalmungSan** [comment] 2021-05-12 14:14
Hi @vnickolov sorry to bother you again, but it seems the [`jersions.json` file](https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/versions.json) is outdated again.
There is no entry for **neo4j** `4.2.6` there is also no entry for the new `1.1.7` of the [**GDS**] plugin.

BTW, would you prefer me to move this to a separate issue?

**Comment by vnickolov** [comment] 2021-05-12 15:53
Hi @BalmungSan, no problem at all, yes, we are aware of the `4.2.6` missing, should be updated soon. I am not aware of GDS 1.1.7 release though, currently 1.1.6 is on the official download page and also is mapped.

**Comment by BalmungSan** [comment] 2021-05-12 15:57
@vnickolov yeah sorru, I got confused; after that I edited the message but it seems I deleted more than needed.
_personal note, not opening issues before coffee_

Thanks for looking into it!

**Comment by vnickolov** [comment] 2021-05-12 15:58
Hi @BalmungSan, the `versions.json` file is now updated and have the entry for Neo4j 4.2.6
