### ISSUE TITLE
Random walk (possibly) not recognizing undirected relationship

### ISSUE THREAD

**Issue by msilva00** [neo4j/graph-data-science#173] opened 2022-03-15 22:56 UTC
**GDS update> 1.6 Not yielding Random Walk results**
GDS v1.8.2.
Neo4j v4.4.

All of the edges in my graph are DIRECTED. But for the purpose of Random Walk traversals, I want to treat them as UNDIRECTED.  
On previous versions GDS v 1.6 I was able to do this by creating the memory projection of the graph the following way:

`CALL gds.graph.create(
                'myGraph',
                '*',
                { undirected: {type: '*', orientation: 'UNDIRECTED'} }
            ) YIELD graphName AS graph, nodeProjection, nodeCount AS nodes, relationshipProjection, relationshipCount AS rels;
`

In my graph, this yields 2210888 nodes, and 661698 relationships.

Then run the Random Walk as follows:
`CALL gds.beta.randomWalk.stream('myGraph',
    {
        walksPerNode:5, walkLength:2, inOutFactor:1
    }
) 
YIELD nodeIds, path
RETURN nodeIds, [node IN nodes(path) | node.name ] AS pages`

Note: in the 'alpha' development (GDS version <1.6) the parameters names have changed. When I specified the 'alpha' development random walk, there were no issues. In the previous version, GDS 1.6 random walks were obtained.

 After updating versions, nothing in my graph has changed except maybe new nodes being added. However the new 'alpha' version of the Random Walk algorithm yields no random walks. I get `(no changes, no records)` as the output. Is it possible that despite specifying UNDIRECTED edges, the random walk is still treating the relationships as directed?

**Comment by adamnsch** [comment] 2022-03-23 10:14
Hi @msilva00,

I will try and reproduce this and get back to you.

**Comment by adamnsch** [comment] 2022-03-23 11:09
Hi agian @msilva00,

I'm not able to reproduce this. If I run your commands on a small toy graph I do get actual `nodeIds` and `pages` back, even if the graph is disconnected when directed. In fact, even if I don't project it as `UNDIRECTED` I get an output. This makes sense since `walkLength` is equal to 2, and thus any directed relationship is a valid walk.

What output do you get if you simply `YIELD nodeIds, path`?

I'm not sure how I can be of further assistance since everything seems to work fine as far as I can tell.

**Comment by knutwalker** [comment] 2022-04-11 13:45
@msilva00 We're closing this for now since we couldn't reproduce the issue. If you have new insights, feel free to re-open the issue.

**Closed by knutwalker** 2022-04-11 13:45 UTC
Labels: BUG
