### ISSUE TITLE
Odd Result on Louvain Community Detection

### ISSUE THREAD

**Issue by andyhegedus** [neo4j/graph-data-science#172] opened 2022-03-07 18:59 UTC
Hi,
Working on graph and have a subgraph which I did a Louvain community detection. The code to create the virtual graph is
CALL gds.graph.create.cypher(
    "BASE_CPC",
    "MATCH (n:patent) WHERE exists {(n:patent)-[:Classified_as]->(a:cpc) where a.subgroup in ['H01L21/0228','H01L21/0229','H01L21/28194','H01L21/3141','H01L45/1616']} RETURN id(n) AS id, labels(n) AS labels",
    "MATCH (a:patent)-[:Cites]->(b:patent) return id(a) AS source, id(b) AS target",
    {validateRelationships: FALSE}
);

The Louvain is done with this
CALL gds.louvain.write('BASE_CPC', { writeProperty: 'CID',consecutiveIds:true,minCommunitySize:10 })
YIELD communityCount, modularity, modularities;

With the important thing to note is that I am using the [:cites] relationship to define the relationship between the nodes.
In looking at the results within Bloom I am filtering by CID to validate the clusters.

In general they make sense, however in looking at this one
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/44418310/157099606-bb30be9c-a247-4bd0-9992-a84870d1475d.png">
 I notice that included in the community is one node that does NOT have a relationship of [:Cites] with the bulk of the nodes. I validated this by selecting all nodes and asking to reveal relationships within Bloom. The coloring on the relationship represent a property key and can be ignored.

Is it possible to have clusters where individual nodes are not connected, it seems to defeat the purpose.
Andy

**Comment by vnickolov** [comment] 2022-03-28 08:01
@andyhegedus thank you for raising this issue.

Can you please provide some additional information

- the output of `gds.graph.create.cypher` would be great, especially the graph schema
- if possible getting the results directly from the graph, using Cypher queries or `gds.louvain.stream`
- if possible a data dump so we can try and reproduce the issue locally

Thank you in advance.

**Comment by knutwalker** [comment] 2022-04-11 13:56
@andyhegedus we're gonna close this issue since we cannot reproduce the problem. If you have more information on the questions that @vnickolov shared above, feel free to re-open the issue.

**Closed by knutwalker** 2022-04-11 13:56 UTC
