### ISSUE TITLE
personal PageRank Thrown 'OutOfMemoryError: unable to create native thread:' under normal use case

### ISSUE THREAD

**Issue by littlemilkwu** [neo4j/graph-data-science#139] opened 2021-12-02 03:29 UTC
continue with issue #132 

In my real use case, I first create an In-memory projected graph which have 6017 nodes and 37819 relations.
Then, I run personal PageRank only 3 times that each time with 2276 nodes as [sourceNodes].

Still face the thread issue when threads come to 4095.

what can I do for this situation ?
I am suffer from this error for a long time....

below are my cypher queries
```
CALL gds.graph.create(
    'UP',
    ['User', 'Post'],
    {
        Action: { 
            orientation: 'UNDIRECTED',
            properties: 'weight'
        }
    }
)
```

```
MATCH (sources:User)
WITH sources
CALL gds.pageRank.stream('UP', {
    sourceNodes: [sources],
    relationshipWeightProperty: 'weight',
    concurrency: 1
})
YIELD nodeId, score
WITH sources, gds.util.asNode(nodeId) as nodes, score
WHERE (nodes.pid IS NOT NULL) AND (NOT (sources)-[]->(nodes))
RETURN sources.uid as source, nodes.pid as pid, score
ORDER BY score DESC
```

It still throw the same error.
(neo4j.log)
![image](https://user-images.githubusercontent.com/44579618/144348953-da06a896-3e31-432f-9847-6d811519c0e9.png)

(query.log)
![image](https://user-images.githubusercontent.com/44579618/144349510-173db43a-5b9d-4346-93b5-9a22c7f7e1e0.png)

(debug.log)
![image](https://user-images.githubusercontent.com/44579618/144349720-a496a0dd-8458-4875-80b0-6d503ba3b595.png)

**Comment by s1ck** [comment] 2021-12-02 09:04
I assume that this caused by an issue with not closing FJ pools on our side. We received a PR recently and will merge it soon: https://github.com/neo4j/graph-data-science/pull/138

Let's leave the issue open until it's merged and you got a chance to test it.

**Comment by s1ck** [comment] 2021-12-03 13:53
@littlemilkwu we merged the change. Feel free to build from source and try it out. We also released 1.7.3 yesterday which contains the fix. Would be nice if you let us know if it fixes your issue. Thanks!

**Comment by littlemilkwu** [comment] 2021-12-03 17:23
@s1ck 
After upgrade to 1.7.3 version,
the issue is completely corrected !
Thx you guys soooooooo much !
You're my lifesaver~

**Comment by s1ck** [comment] 2021-12-03 17:29
Sweet. Thanks for the quick reply! Please continue reporting issues if you find any, this is super useful feedback.

**Closed by s1ck** 2021-12-03 17:29 UTC
Labels: BUG
